<?php

return [
    'theme_keywords' => [
        'meaning',
        'future',
        'human',
        'flourishing',
        'creativity',
        'creative',
        'reading',
        'art',
        'ai',
        'intelligence',
        'improvement',
        'writing',
        'education',
        'productivity',
    ],
    'idea_keywords' => [
        'framework',
        'lesson',
        'principle',
        'idea',
        'strategy',
        'practice',
        'model',
        'system',
        'habit',
        'workflow',
        'design',
    ],
    'political_penalty_keywords' => [
        'election',
        'partisan',
        'culture war',
        'propaganda',
        'campaign',
    ],
    'label_keywords' => [
        'Meaning' => ['meaning', 'purpose', 'flourishing'],
        'Future' => ['future', 'forecast', 'tomorrow'],
        'Business' => ['business', 'startup', 'market', 'sales'],
        'Tutorial' => ['tutorial', 'how to', 'guide', 'walkthrough'],
        'Podcast' => ['podcast', 'episode'],
        'Creativity' => ['creativity', 'creative', 'art', 'design'],
        'CyberSecurity' => ['security', 'cybersecurity', 'hacking'],
        'AI' => ['ai', 'artificial intelligence', 'llm', 'model'],
        'Essay' => ['essay', 'reflection'],
        'Video' => ['video', 'watch'],
        'Conversation' => ['conversation', 'interview', 'discussion'],
        'Optimization' => ['optimize', 'optimization', 'efficiency'],
        'Personal' => ['personal', 'life', 'mindset'],
        'Writing' => ['writing', 'writer', 'essay'],
        'Health' => ['health', 'sleep', 'exercise'],
        'Technology' => ['technology', 'software', 'engineering'],
        'Education' => ['education', 'learning', 'teach'],
        'Leadership' => ['leadership', 'leader', 'manage'],
        'Mindfulness' => ['mindfulness', 'meditation', 'presence'],
        'Innovation' => ['innovation', 'invent', 'new idea'],
        'Culture' => ['culture', 'society', 'community'],
        'Productivity' => ['productivity', 'workflow', 'focus'],
        'Science' => ['science', 'research'],
        'Philosophy' => ['philosophy', 'ethics', 'meaning'],
    ],
];
